title: Jack's Recipes
description: Jack's Recipes
baseurl: "/"
url: "https://recipes.jackthomas.io"
theme: minima
plugins:
  - jekyll-feed
exclude:
  - README.md
header_pages:
  - about.md
  - all.md
  - categories.md
permalink: :title.html
collections:
  recipes:
    output: true
    permalink: :title.html
emptyArray: []
